In [1]:
#install numpy
!pip install numpy
import numpy as np

In [2]:
A=[1,2,3,"a","b"]

In [3]:
type(A)

list

In [4]:
a=[1,3]

In [5]:
type(a) #determining the datatype 

list

In [6]:
#printing 10 floats of zeroes
g=np.zeros(10)

In [7]:
g

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
m=np.zeros(5)
m

array([0., 0., 0., 0., 0.])

In [9]:
#3 rows/arrays with 4 elements
q=np.zeros((3,4))
q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#print out the length
q.shape

(3, 4)

In [11]:
#finding the type of array
type(q)

numpy.ndarray

In [13]:
#print out 10 zeros with an element
g.shape=(10,1)
g

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
#printing out the length of g
g.shape

(10, 1)

In [16]:
#printing out the elements in ones five times
z=np.ones(5)
z

array([1., 1., 1., 1., 1.])

In [17]:
type(z[1]) #finding the datatype of an element of an array

numpy.float64

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
l=np.empty(3)
l

array([ 1.31073208e-311,  0.00000000e+000, -4.94065646e-324])

In [20]:
l=np.empty(12)
l

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#creating a one dimensional array with a list
np.array([1,2,3])

array([1, 2, 3])

In [24]:
#making a list into an array
l=[1,2,3,4]
r=np.array([l])
r

array([[1, 2, 3, 4]])

In [42]:
type(l)

list

In [25]:
type(r)

numpy.ndarray

In [26]:
#storing in a variable
y=np.array([1,2,3])
print(y)

[1 2 3]


In [27]:
#storing in a variable with strings as an array
s=np.array(["A","B","C"])
print(s)

['A' 'B' 'C']


In [28]:
type(s)

numpy.ndarray

# Dimensions and Operators Exercise

In [29]:
#checking the dimensions of a
a=np.array([1,2,3])
print(a)
print(a.ndim) #snippet for dimension

[1 2 3]
1


In [31]:
#creating a 2d array
d=np.array([(1,2,3),(1,2,3)])
print(d)

[[1 2 3]
 [1 2 3]]


In [32]:
#cheack the dimension type(2d)
print(d.ndim)

2


In [33]:
p=np.array([[(1,2,3),(4,5,6)]]) #for 3d array
print(p.ndim)

3


In [34]:
p

array([[[1, 2, 3],
        [4, 5, 6]]])

In [37]:
t=np.array([[(1,2,3)],[(4,5,6)],[(7,8,9)]])
t

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [38]:
print(t.ndim)

3


In [39]:
#the question mark with a shift and tab key gives as documentation
?p

In [40]:
#the question mark with a shift and tab key gives as documentation of the purticular parameter
?p.shape

In [41]:
#the variable p less than 5. Print a boolean
p<5

array([[[ True,  True,  True],
        [ True, False, False]]])

In [43]:
#the variable p greater than 2 . Print a boolean
p>2

array([[[False, False,  True],
        [ True,  True,  True]]])

In [44]:
#the variable p equals to 3. Print a boolean
p==3

array([[[False, False,  True],
        [False, False, False]]])

In [45]:
#the variable p not equals to 3. Print a boolean
p!=3

array([[[ True,  True, False],
        [ True,  True,  True]]])

# Byte , Type and size

In [46]:
#check the byte size of each element
n=np.array([1,2,3])
print(n.itemsize)

4


In [47]:
print(n.dtype)

int32


In [48]:
print(len(n))

3


In [49]:
#check the datatype
q=np.array([1,2,3])
print(q.dtype)

int32


In [50]:
#check the length of elements
w=np.array([1,2,3,4])
print(w.size)

4


# Range argument of np.arrange()

In [51]:
#this works with arrays with parameters:start,stop and step.You have to pass atleast one of the parameters.the default value of step is 1 if no value is provided.

In [52]:
#this prints elements from 1 to 10 in the step of 3
np.arange(start=1,stop=10,step=3)

array([1, 4, 7])

In [53]:
np.arange(1,10,3)

array([1, 4, 7])

In [54]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [55]:
#print from 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Shape and Reshaping

In [56]:
u=np.array([(1,2,3,7),(5,9,7,20)])
print(u.shape)

(2, 4)


In [57]:
#check the shape(array(2) and elements(3))
y=np.array([(1,2,4),(1,6,3)])
print(y.shape)

(2, 3)


In [58]:
y

array([[1, 2, 4],
       [1, 6, 3]])

In [59]:
y.ndim

2

In [60]:
#reshaping from 1d to 2d;4 arrays with 3 elements
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g=b.reshape(4,3)
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
#convert to 1d array
b=np.array([[1,2,3],[3,5,4]])
z=b.reshape(-1)
z

array([1, 2, 3, 3, 5, 4])

In [63]:
#print all in a line
b=np.array([[1,2,3],[3,5,4]])
print(b.ravel())

[1 2 3 3 5 4]


In [85]:
#this prints elements from 0 to 11,4 arrays with each having 3 elements
b=np.arange(12).reshape(4,3)
b


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
#this prints from 0 to 14,3 arrays with each having 5 elements
a=np.arange(15).reshape(3,5)

In [66]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
#reshape converting 2 rows , 4 elements to 4 rows, 2 elements
p=np.array([(1,2,3,5),(2,4,5,5)])
print(p)
p=p.reshape(4,2)
print(p)

[[1 2 3 5]
 [2 4 5 5]]
[[1 2]
 [3 5]
 [2 4]
 [5 5]]


# slicing


In [68]:
#this print element at zero index

In [69]:
n=np.array([1,2,3,4,19,6,7])
print(n[0])

1


In [70]:
#this print element from 0 to 4th index excluding the 5th index
print(n[1:5])

[ 2  3  4 19]


In [71]:
print(n[0:2])

[1 2]


In [72]:
print(n[:])

[ 1  2  3  4 19  6  7]


In [73]:
#printing the last element
print(n[-1])

7


In [74]:
#printing elements from the 4th element to the end
print(n[4:])

[19  6  7]


In [75]:
#printing the first 4 elements
print(n[:4])

[1 2 3 4]


# Sum , max,min and linspace

In [76]:
#printing 5 values from 1 to 3
b=np.linspace(1,3,5)
b

array([1. , 1.5, 2. , 2.5, 3. ])

In [77]:
#printing 5 values from 2 to 10
y=np.linspace(2,10,5)
y

array([ 2.,  4.,  6.,  8., 10.])

In [78]:
#printing the maximum number in  an array
m=max(y)
m

10.0

In [79]:
#printing the minimum number in an array
mi=min(y)
mi

2.0

In [80]:
#sum of elements
s=sum(y)
s

30.0

# Random functions

In [81]:
from numpy import random

In [86]:
#generate ramdom integers from 0 to 30
x=random.randint(50)
x

10

In [89]:
m=random.randint(6)
m

5

In [90]:
#generate random float between 0-1
x=random.rand()
print(x)

0.7737459381609207


In [91]:
#generate a 1d array of 10 1d elements
y=random.rand(10)
print(y)

[0.56630278 0.80420876 0.23620976 0.35670037 0.27359329 0.15870351
 0.82913563 0.67148058 0.10636664 0.38986069]


In [92]:
#generate a random array with 3 rows and 4 columns
y1=random.rand(3,4)
print(y1)

[[0.14760721 0.97417443 0.25354811 0.49778923]
 [0.25778838 0.76025985 0.07503078 0.97126493]
 [0.7368615  0.25630668 0.64998741 0.92226275]]


In [93]:
#generate 10 random numbers from 0-100 
n=random.randint(100,size=10)

In [94]:
n

array([26, 73, 95, 13, 12, 14, 97, 44, 82, 86])

In [95]:
n.ndim

1

In [96]:
#select a value from an array
e=random.choice([7,3,10,9])

In [97]:
e

3

In [98]:
#generate a 2d array with 3 rows and 4 columns, to each row picking from the listed values
a=random.choice([3,5,7,9],size=(3,4))
a

array([[5, 5, 9, 9],
       [5, 3, 3, 7],
       [7, 9, 7, 9]])

# Axis=AXIS 1=ROWS and AXIS 0=COLUMNS

In [99]:
#this sums the row
a=np.array([(1,2,3),(4,5,6)])
print(a.sum(axis=1))

[ 6 15]


In [100]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
#this sums the columns
a=np.array([(1,2,3),(4,5,6)])
print(a.sum(axis=0))

[5 7 9]


# Stacking

In [104]:
#vertical stacking
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(1,2,3)])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [105]:
#horizontal stacking
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(1,2,3)])
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [4 5 6 1 2 3]]


---

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a[1:2,2:3]

array([[6]])

In [4]:
a[1,2]

6